version: '3.9'

services:
  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_USER_PASSWORD=admin
      - INFLUXDB_ADMIN_USER_TOKEN=
      - INFLUXDB_ADMIN_USER_TOKEN_FILE=
      - INFLUXDB_DB=k6database
    volumes:
      - /data/influxdb:/bitnami/influxdb
    networks:
      - hubswicth
    ports:
      - "8086:8086"
  
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - hubswicth
    ports:
      - "3001:3000"
 



networks:
  hubswicth:
    driver: bridge
